### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by daemir** [Anyline/react-native-image-to-pdf#1]
I'm using native paths (file///var/...) and whenever I create PDFs as described in the docs, I'm just getting blank pages

**Comment by JonasLaux** [comment]
Hi,
are you speaking of iOS or Android?

**Comment by Balmurugan96** [comment]
same issue for me also in ios react native

**Comment by sandeep5793** [comment]
I am also getting the same issue while implementing this module.
getting the blank page after opening the generated pdf..didnt know how to solve it.
any solutions?

**Comment by JonasLaux** [comment]
How did you start the App? Can you maybe start it trough Xcode and read the log?
Is it maybe related to this? 
https://github.com/Anyline/react-native-image-to-pdf/issues/5

**Comment by karalundi2019** [comment]
I have the same issue, more than a year and there's not a solution?

**Comment by JonasLaux** [comment]
If you have the same issue. Could you provide some logs from XCode for it?

**Comment by karalundi2019** [comment]
Hi @JonasLaux  It solved by removing "file:///private" from path and just let the path start with "/var/...".  I don't know if this is a real solution but it's working for me now.

PS: Before that there were no errors or logs in Xcode, the process was correct and generated a blank pdf.

**Comment by JonasLaux** [comment]
ok, thanks for sharing!
