### ISSUE TITLE
No PDF Generating

### ISSUE THREAD

**Issue by ashishrokr** [Anyline/react-native-image-to-pdf#2]
RNImageToPdf.createPDFbyImages({
         imagePaths: [`data:image/jpeg;base64,${base64String}`,`data:image/jpeg;base64,${base64String}`],
         name: "PDF_Name"
       });     
i have array of base64 string,want to generate PDF from that base64 string,but no pdf generation  @JonasLaux

**Comment by JonasLaux** [comment]
hi @ashishrokr ,
what exactly is your question on this one?
Also, base64 is not implemented yet.

**Comment by dishantjaykasodhan-kiwi** [comment]
> hi @ashishrokr , what exactly is your question on this one? Also, base64 is not implemented yet.
 is this implimented Now ?
