### ISSUE TITLE
[Error: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference]

### ISSUE THREAD

**Issue by oVuVanChuyen** [Anyline/react-native-image-to-pdf#20]
I am using react-native 0.61.1 to build my app. When i used lib for android to save pdf file. I getting this error:
```[Error: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference]```
Could  anyone to help me?

**Comment by SUJITHBHAT** [comment]
I am facing this same issue. Any fix?

**Comment by SUJITHBHAT** [comment]
I think the path you are passing starts with file://
pass the path "/path/to/image-12d5b362-d4d8-45f5-b762-4ad9e47751a7.jpg" instead of
"file:///path/to/image-12d5b362-d4d8-45f5-b762-4ad9e47751a7.jpg"

**Comment by zedtux** [comment]
Thank you @SUJITHBHAT, it solved the issue.

**Comment by ederviera** [comment]
good night I have the same problem I have when creating a pdf based on a loaded photo I get this error:

Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth ()' on a null object reference

private void createPdf(){

        WindowManager wm = (WindowManager) getActivity().getSystemService(Context.WINDOW_SERVICE);
        Display display = wm.getDefaultDisplay();
        DisplayMetrics displaymetrics = new DisplayMetrics();
        getActivity().getWindowManager().getDefaultDisplay().getMetrics(displaymetrics);
        float hight = displaymetrics.heightPixels ;
        float width = displaymetrics.widthPixels ;

        int convertHighet = (int) hight, convertWidth = (int) width;


        PdfDocument document = new PdfDocument();
        PdfDocument.PageInfo pageInfo = new PdfDocument.PageInfo.Builder(bitmap.getWidth(), bitmap.getHeight(), 1).create();
        PdfDocument.Page page = document.startPage(pageInfo);

        Canvas canvas = page.getCanvas();

        Paint paint = new Paint();
        paint.setColor(Color.parseColor("#ffffff"));
        canvas.drawPaint(paint);

        bitmap = Bitmap.createScaledBitmap(bitmap, bitmap.getWidth(), bitmap.getHeight(), true);

        paint.setColor(Color.BLUE);
        canvas.drawBitmap(bitmap, 0, 0 , null);
        document.finishPage(page);


        // GRABAR LA IMAGEN

        File root = new File(Environment.getExternalStorageDirectory(), "SMART LIBRARY PDF");

        if (!root.exists()){

            root.mkdir();
        }

        File file = new File(root, "PruebaPDFsMART.PDF");
        try {

            FileOutputStream fileOutputStream = new FileOutputStream(file);
            document.writeTo(fileOutputStream);


        } catch (IOException e) {
            e.printStackTrace();
            Toast.makeText(getActivity(), "El error es: " + e.toString(), Toast.LENGTH_LONG).show();
        } //ppal createpdf

        // close the document
        document.close();



    }

**Comment by SUJITHBHAT** [comment]
@ederviera  the path you are passing should be of the format  "/path/to/image-12d5b362-d4d8-45f5-b762-4ad9e47751a7.jpg" instead of
"file:///path/to/image-12d5b362-d4d8-45f5-b762-4ad9e47751a7.jpg"

**Comment by ederviera** [comment]
thank you very much, you solution is good

**Comment by GuvanchBayryyyev** [comment]
Can anybody give example please, how to set path. For example, my path is: '../../assets/icon.png

**Comment by VikasSahu** [comment]
Hi  @ederviera @zedtux @oVuVanChuyen @JonasLaux @GuvanchBayryyyev @frenberg @SUJITHBHAT 

This is the uri/path I am getting -  **file:///data/user/0/com.dragg.com/cache/ReactNative-snapshot-image2555018024690974287.jpg**

Now as per the above comment I am changing my path name to resolve this issue is  - **/data/user/0/com.draggapp/cache/ReactNative-snapshot-image2555018024690974287.jpg**

Still getting the same error  -  **[Error: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference]**

My code is 

` const options = {
       // imagePaths: ['/data/user/0/com.draggapp/cache/ReactNative-snapshot-image2961034648508671787.jpg'],
        imagePaths: [path],
        name:  'PDFNameSample',
        maxSize: { // optional maximum image dimension - larger images will be resized
          width: 900,
          height: Math.round(windowHeight / windowWidth * 900),
        },
        quality: .7, // optional compression paramter
      };
      console.log("Check 3 , ",JSON.stringify(options));

      const data = await RNImageToPdf.createPDFbyImages(options);`

Please suggest how to resolve this issue.
