### ISSUE TITLE
Pdf compression

### ISSUE THREAD

**Issue by armin23615** [Anyline/react-native-image-to-pdf#26]
My pdf is little blurry. Is it possbile to generate it without compressing?

**Comment by gseebacher** [comment]
Hi Armin,
the pdf is created without compression.
Did you check if the camera focused correctly?

**Comment by abishekraj-a** [comment]
> My pdf is little blurry. Is it possbile to generate it without compressing?

I have the same issue on iOS alone, is there any way to fix this ?
