### ISSUE TITLE
Unable to convert [images] to pdf file using react-native-image-to-pdf

### ISSUE THREAD

**Issue by mahendraios** [Anyline/react-native-image-to-pdf#28]
Hi,
I'm trying to convert [images] array to pdf file. When I call RNImageToPdf.createPDFbyImages(options)

I'm getting this error:

TypeError: null is not an object (evaluating '_reactNativeImageToPdf.default.createPDFbyImages')]
  line: 95677,
  column: 81,
  sourceURL: 'http://192.168.3.43:8081/index.bundle?platform=ios&dev=true&minify=false' }

**Comment by dharmikvyas** [comment]
Hi,
have you found any working example of this? is your problem solved? Please let me know I have same issue

**Comment by djcruz93** [comment]
Hey, even I am also facing the same issue. I am using expo-client to build and test my application. Do let me know if react-native-image-to-pdf is not supported by expo. Let me know the steps to run natively on android studio after linking it using react-native cli.

**Comment by Piyush132000** [comment]
hey , i am phasing problem file not supported after  creation of file

**Comment by frenberg** [comment]
This usually comes from incorrect input. You must pass the path to the source files in the array and it should be a unix type path, not urls.

**Comment by Piyush132000** [comment]
please  define unix type path

i am passing uri of image your mean image name only

**Comment by frenberg** [comment]
Usually the uri looks like file://path, but you should only use the absolute path

I have code like this where images is the array of URIs

```
const stripFilePrefix = (path: string): string => path.split('file://').pop();
const options = {
	imagePaths: images.map((image) => stripFilePrefix(image.uri)),
	name: fileName.substring(0, fileName.indexOf('.pdf')), // library adds .pdf
};
return RNImageToPdf.createPDFbyImages(options).then(({ filePath }) => ({
	documentPath: `file://${filePath}`,
	documentType: 'application/pdf',
	documentName: fileName,
}));

```

**Comment by Piyush132000** [comment]
hey bro please share full code please
of React native Thanku

**Comment by frenberg** [comment]
This is not an issue with the library, ask your question on stackoverflow. It's a great place for questions like this, share your code there and someone will help you 👍
