### ISSUE TITLE
react-native-image-to-pdf gives atempt to invoke virtual method error

### ISSUE THREAD

**Issue by g-mahendra** [Anyline/react-native-image-to-pdf#30]
Whether I use react-native-image-to-pdf or react-native-pdf-lib to create a pdf in my react-native app, I get the error [Error: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference]. I am using react-native-image-crop-picker to pick multiple iages Here is my code

import * as React from 'react';
import {View, Text, Button} from 'react-native';
import ImagePicker from 'react-native-image-crop-picker';
import RNImageToPdf from 'react-native-image-to-pdf';

const App = () => {
  var photoPath = [];
  const handlePick = () => {
    ImagePicker.openPicker({
      multiple: true,
    })
      .then((image) => {
        console.log(image.path);
        photoPath.push(image.path);
      })
      .then(async () => {
        try {
          const options = {
            imagePaths: photoPath,
            name: 'PDFName',
            maxSize: {
              // optional maximum image dimension - larger images will be resized
              width: 900,
              height: Math.round((deviceHeight() / deviceWidth()) * 900),
            },
            quality: 0.7, // optional compression paramter
          };
          const pdf = await RNImageToPdf.createPDFbyImages(options);
          console.log(pdf.filePath);
        } catch (e) {
          console.log(e);
        }
      });
  };
};

export default App;

**Comment by g-mahendra** [comment]
Sorry for code snippet. This is my first question

**Comment by frenberg** [comment]
Hi,

you need to pass the path to the files and not the file://-url. If you examine your data you will probably notice that what you are passing is the "file://"-url.
We should really improve the error handling and docs on that because you are not the first person to experience this, sorry 😞

**Comment by frenberg** [comment]
have a look at this if something is unclear https://github.com/Anyline/react-native-image-to-pdf/issues/20
