### ISSUE TITLE
Error: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth() on a null object reference

### ISSUE THREAD

**Issue by tuxlan** [Anyline/react-native-image-to-pdf#31]
This is my settings:

react-native-cli: 2.0.1
react-native: 0.62.2

I had to override the minSDK version to 19
Then when I implemented the code

```
converToPDF = async(imagePath) => {
    console.log("Conver to PDF...", imagePath);
    try {
      const options = {
        imagePaths: [imagePath],
        name: "PDFName",
        maxSize: {
          width: 900,
          height: Math.round(deviceHeight / deviceWidth * 900),
        },
        quality: .9,
      };

      const pdf = await RNImageToPdf.createPDFbyImages(options);
      this.saveImage(pdf.filePath, true);
    } catch(error) {
      console.log(error);
    }
  }
```

I got the error:  [Error: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference]

**Comment by erikaperugachi** [comment]
The the close issues: https://github.com/Anyline/react-native-image-to-pdf/issues/20

**Comment by tuxlan** [comment]
> Check the close issues: #20

Thanks! :D

**Comment by brandtiwari007** [comment]
"storage/emulated/0/Pictures/IMG_20201201_134646.jpg", i am giving this path ,still facing same  error

**Comment by brandtiwari007** [comment]
i am using same code ,in samsung S9  device it is running fine ,but in samsung S10  i am getting  this Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference.

**Comment by frenberg** [comment]
It should be a leading '/' since that is a full path. with no leading / it is considered a relative path and would search in the current working directory for a 'storage/emulated...'-path

**Comment by brandtiwari007** [comment]
> It should be a leading '/' since that is a full path. with no leading / it is considered a relative path and would search in the current working directory for a 'storage/emulated...'-path

thanks frenberg

**Comment by brandtiwari007** [comment]
> It should be a leading '/' since that is a full path. with no leading / it is considered a relative path and would search in the current working directory for a 'storage/emulated...'-path

i have tried  it by giving '/' as a leading ,getting same error in S10   
 "/storage/emulated/0/Pictures/IMG_20201201_134646.jpg",
