### ISSUE TITLE
How can i get the pdf image to be vartical or horizontal?

### ISSUE THREAD

**Issue by RogelioLB** [Anyline/react-native-image-to-pdf#32]
When i use it with images that are originallly vertical it puts them horizontally making them look bad, howw can i solve that?
And that only happen with photos taken on the phone

**Comment by meliodev** [comment]
It happens to me also when taken by camera

**Comment by visheshagomic** [comment]
https://github.com/Anyline/react-native-image-to-pdf/pull/29/commits/792ad8783ea18c2520cbd8b42c73a27e93ef278e



check this man

**Comment by luccadumas** [comment]
check this man

**Comment by RogelioLB** [comment]
Thank you for everyone, it worked
