### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by manoel17rpn** [Anyline/react-native-image-to-pdf#7]
{ [TypeError: undefined is not an object (evaluating '_reactNativeImageToPdf2.default.createPDFbyImages')]
      line: 146842,
      column: 52,
      sourceURL: 'http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false' }

any solution?

**Comment by manoel17rpn** [comment]
My code: 

`const pdf = RNImageToPdf.createPDFbyImages({ imagePaths: images, name: 'PDFName'});`

images is an array. I am following the doc

**Comment by JonasLaux** [comment]
Hey,
can you log the array "images" right before the call? Are you sure it is defined?

**Comment by manoel17rpn** [comment]
Ops, I am sorry. You can close this issue. It`s working. Thank you.

**Comment by JonasLaux** [comment]
Hey, 
hm this seems to be a wrong path. Can you try just the absolute path without the "file://"

**Comment by nik0504** [comment]
i am getting same issue

**Comment by nik0504** [comment]
i am unable to convert image to pdf
const pdf = await RNImageToPdf.createPDFbyImages({ imagePaths: userId.uri, name: 'PDFName'});
this is userId.uri 
file:/data/user/0/host.exp.exponent/cache/ExperienceData/%2540nik050505%252Fproject_1/ImagePicker/bf6659d4-c983-4b24-b675-20e4da6013a4.jpg

**Comment by frenberg** [comment]
> i am unable to convert image to pdf
> const pdf = await RNImageToPdf.createPDFbyImages({ imagePaths: userId.uri, name: 'PDFName'});
> this is
> file:/data/user/0/host.exp.exponent/cache/ExperienceData/%2540nik050505%252Fproject_1/ImagePicker/bf6659d4-c983-4b24-b675-20e4da6013a4.jpg

Hey

same problem and same solution probably. imagePaths should be an array of absolute paths. Do try without the 'file://' part. It should be like:
`const pdf = await RNImageToPdf.createPDFbyImages({imagePaths: ['/path/to/image1.png'], name: name: 'PDFName'})`

You could do something like `const pdf = await RNImageToPdf.createPDFbyImages({ imagePaths: [userId.uri.split('file://').pop()], name: 'PDFName'});` if you know userid.uri is never null

**Comment by truyenle16398** [comment]
> > i am unable to convert image to pdf
> > const pdf = await RNImageToPdf.createPDFbyImages({ imagePaths: userId.uri, name: 'PDFName'});
> > this is
> > file:/data/user/0/host.exp.exponent/cache/ExperienceData/%2540nik050505%252Fproject_1/ImagePicker/bf6659d4-c983-4b24-b675-20e4da6013a4.jpg
> 
> Hey
> 
> same problem and same solution probably. imagePaths should be an array of absolute paths. Do try without the 'file://' part. It should be like:
> `const pdf = await RNImageToPdf.createPDFbyImages({imagePaths: ['/path/to/image1.png'], name: name: 'PDFName'})`
> 
> You could do something like `const pdf = await RNImageToPdf.createPDFbyImages({ imagePaths: [userId.uri.split('file://').pop()], name: 'PDFName'});` if you know userid.uri is never null

Hi @frenberg ,
I have the same problem and I tried your solution but it it not work. Pls support, tks
+ My code: const pdf = await RNImageToPdf.createPDFbyImages({ imagePaths: [imageURI], name: 'PDFName'});
+ My imageURI: /data/user/0/host.exp.exponent/cache/ExperienceData/%2540truyenle123%252Ffwg-pickdy-sunmi/ReactNative-snapshot-image493201787672251380.png

**Comment by MuhammadRafeh** [comment]
Same Error: [TypeError: null is not an object (evaluating '_reactNativeImageToPdf.default.createPDFByImages')]

Shape of URI is  like this below: 
content://com.images.provider/root/storage/emulated/0/Pictures/images/image-50f25b3c-3073-4939-b6a7-92943a0e27b5.jpg

How to solve it, Can anybody help me with this.
